### ISSUE TITLE
Tor connections 

### ISSUE THREAD

**Issue by ip-config** [atomiclabs/hyperdex#288]
Hello,
Kmd coin is privacy coin!
it's good idea to add in settings : tor connections ?
Regards

**Comment by lukechilds** [comment]
I'm not sure `marketmaker` will work very well over Tor due to requiring it's own ports on a public IP.

@jl777?

**Comment by jl777** [comment]
no idea, never used tor

**Comment by sindresorhus** [comment]
We have decided not to support this. It just won't ever be feasible.

- Marketmaker makes a lot of connections, this would be very slow because of the way Tor works.
- We would be a big burden on the Tor network because we call both marketmaker and various network services on a frequent interval.
- > Marketmaker does not use TLS for Electrum servers so the exit nodes could mess up your trades, and even potentially reverse trades if your are trading with the entity that controls the Tor node. Which isn’t as unlikely as it sounds if they can see all your traffic, they could spin up Bobs with low prices for coins they can see you are interested in. - @lukechilds
