### ISSUE TITLE
HOdlcoin generates wrong deposit addresses

### ISSUE THREAD

**Issue by AmiT177** [atomiclabs/hyperdex#289]
![yk6p49h](https://user-images.githubusercontent.com/8685831/40380037-8ceaf694-5e00-11e8-9fa0-42f0a5b08db1.png)

HOdlcoin addresses start with H

**Comment by lukechilds** [comment]
This is caused by the `HODL` Komodo asset chain using the same ticker as Hodlcoin. We have `HODLC` as the ticker for Hodlcoin in our config, however it looks like at some point they changed to HODL: https://coinmarketcap.com/currencies/hodlcoin/

```js
	{
		coin: 'HODL',
		asset: 'HODL',
		rpcport: 14431,
		electrumServers: [
			{
				host: 'electrum1.cipig.net',
				port: 10009,
			},
			{
				host: 'electrum2.cipig.net',
				port: 10009,
			},
		],
	},
	{
		coin: 'HODLC',
		name: 'Hodlcoin',
		rpcport: 11989,
		pubtype: 40,
		p2shtype: 5,
		wiftype: 168,
		txfee: 5000,
		electrumServers: [
			{
				host: 'hodl.amit.systems',
				port: 17989,
			},
			{
				host: 'hodl2.amit.systems',
				port: 17989,
			},
		],
	},
```

You can actually currently use both, `HODLC` will give you the correct address:

<img width="308" alt="screen shot 2018-05-25 at 11 45 32 am" src="https://user-images.githubusercontent.com/2123375/40526517-4a81e782-6011-11e8-8492-5aa9ce1e3509.png">


<img width="440" alt="screen shot 2018-05-25 at 11 45 44 am" src="https://user-images.githubusercontent.com/2123375/40526521-4f064ec4-6011-11e8-97dc-71c0a5794a2c.png">

@sindresorhus I think the only reasonable solution here is to remove one. Ticker symbols should be unique. We shouldn't bend over backwards to support coins that don't check if the ticker symbol they want to use is free or not. Thoughts?

**Comment by AmiT177** [comment]
ah alright, thanks for explaining it.
also, HODLcoin (hodlc) is on the market since 2016, not sure what about the Komodo asset.

**Comment by lukechilds** [comment]
No problem, thanks for letting us know, good catch.

Are you aware if they recently changed their ticker to `HODL`?

**Comment by AmiT177** [comment]
I have no idea :/

**Comment by AmiT177** [comment]
A solution could be changing the Komodo asset one name to HODL instead of HOdlcoin, and keeping the ticket the same as it is now

**Comment by lukechilds** [comment]
Btw @sindresorhus if you tackle this for a new release. Can you check if users have trade history containing `HODL` or `HODLC` and then we completely remove the currencies if it breaks anything. I think it will, as we won't auto request the CMC prices for them anymore.

>A solution could be changing the Komodo asset one name to HODL instead of HOdlcoin, and keeping the ticket the same as it is now

That's a nice solution visually, but under the hood all our code relies on the ticker symbols being unique to be able to differentiate between currencies. That's what's causing the current issues with duplicate name and USD price.

We will probably try to get some custom logic that handles cases like this to make it appear visually they are using the same ticker but still have different tickers under the hood.

**Comment by AmiT177** [comment]
Uh alright, understandable

**Comment by FreeTrade** [comment]
Is the Komodo 'HODL' asset still live? If so where can I get more information?

If it is now defunct, I'd suggest removing it and using HODL as the ticker for HOdlcoin. HOdlcoin has always used this ticker, and is listed on CoinMarketCap, CoinExchange and Yobit(insolvent).

**Comment by jorian** [comment]
https://github.com/particle4dev/hyperdex/issues/13 HODLC coin removed
