### ISSUE TITLE
Larger swap message

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#404]
When I try to do a BEER/PIZZA swap with a larger than usual amount I get the below message. The first part of the message makes sense about the deposit size but the second instruction wouldn't work if I just deposited more and tried a larger swap. 

Version: alpha 8
OS: win 10
Errors: below
Severity: Low (3)

![image](https://user-images.githubusercontent.com/22251770/42292193-cc5d427c-7f9e-11e8-91ce-cc10caa2a7e3.png)

**Comment by lukechilds** [comment]
Thanks for reporting, we're aware the errors in HyperDEX often aren't that helpful. This is because almost all the errors come direct from `marketmaker`, not from HyperDEX.

The way error reporting works in `marketmaker` is very limited and doesn't give us a lot of options to handle them better.

We've reported the issue upstream but doesn't look like it will be fixed soon. We probably won't be able to implement better messages in HyperDEX until we get better error reporting in `marketmaker` v2.

Relevant issues:
https://github.com/jl777/SuperNET/issues/717
https://github.com/jl777/SuperNET/issues/594

**Comment by sindresorhus** [comment]
Closing this in favor of https://github.com/atomiclabs/hyperdex/issues/180
