### ISSUE TITLE
Create portfolio issue

### ISSUE THREAD

**Issue by capital-technologies** [atomiclabs/hyperdex#519]
```
Unhandled Promise Rejection
NonError: { code: 'ENAMETOOLONG', errno: 'ENAMETOOLONG', syscall: 'spawn' }
    at module.exports.input (app://-/bundle.js:124451:10)
    at handleError (app://-/bundle.js:124325:9)
    at reason (app://-/bundle.js:124370:4)
    at invokeFunc (app://-/bundle.js:124635:19)
    at trailingEdge (app://-/bundle.js:124682:14)
    at timerExpired (app://-/bundle.js:124670:14)
```

**Comment by lukechilds** [comment]
Is this when you try to create an additional portfolio or when creating your first portfolio with the first run dialogue?

**Comment by capital-technologies** [comment]
This happens when I am creating the first portfolio. I didn't have this issue in the Nightly Build

**Comment by sindresorhus** [comment]
The `ENAMETOOLONG` error means the file name was too long. So it seems the file path to `marketmaker` is too long for some reason when we spawn `marketmaker`, since we use an absolute path to it.

@capital-technologies At what path do you run HyperDEX from? Can you try moving the app to your user home directory and see if that fixes it?

**Comment by jenbuzz** [comment]
I'm having the same issue. Both in v0.1.0 and in the latest nightly build. I tried moving it to another location and that didn't change anything. Running it on Windows 10.

**Comment by sindresorhus** [comment]
A new release is out that fixes this: https://github.com/atomiclabs/hyperdex/releases/latest
