### ISSUE TITLE
Login depreciation error

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#535]
After login I consistently receive the below Buffer error in the console

Version: 0.1.3
OS: Win 10
Errors: below
Severity: Medium

![image](https://user-images.githubusercontent.com/22251770/46158466-e4b1e680-c24b-11e8-8cb8-96739ea6555c.png)

**Comment by sindresorhus** [comment]
This is now fixed in the latest version. It might still show on up Linux sometimes though. I have looked into it and couldn't figure out why the fix didn't always work on Linux. I'm gonna leave it as-is as it's just a warning and the warning itself is coming from dependencies we use and not the app, so fixing those warning is out of our control. If you're on Linux and don't like seeing it, just disable Debug mode (which is meant for advanced user anyway) in the Help menu.
