### ISSUE TITLE
Failed swap after Alice payment

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#536]
I created a failed swap after 3/5 Alice payment causing lost of funds. 

Version: 0.1.3
OS: Win 10
Errors: below
Severity: High

![image](https://user-images.githubusercontent.com/22251770/46158757-90f3cd00-c24c-11e8-837f-0344cd4bb8be.png)

**Comment by sindresorhus** [comment]
According to https://docs.komodoplatform.com/barterDEX/MarketmakerErrors.html, error `-1007` means:

> "error waiting for bobpayment” - Swap failed at 4/7. Bob failed to send bobpayment.

The funds are most likely not lost. You just need to wait until the timelock expires.

From internal notes by @lukechilds:

> there are three possible outcomes:
> - if you quit after `bobpayment` has been sent but before you claim it and you weren’t offline for long you should claim `bobpayment` with an `alicespend` tx. This is a normal atomic swap and has recovered as if you were never offline
> - If Bob never sends `bobpayment` you will need to wait for the 2 hour timelock to expire on `bobdeposit` then you should claim that with an `aliceclaim` tx. This gives you a 12.5% bonus at Bobs expense to punish him for not sending `bobpayment`
> - If Bob never sends any payment but you already sent `alicepayment`, you need to wait 4 hours for the `alicepayment` timelock to expire. The you should be able to reclaim your funds with an `alicereclaim` tx. You don’t get the funds you wanted and you lose the dexfee but you get your original funds back (edited)
so every scenario should result in you either getting the funds you wanted, getting the funds you wanted + 12.5%, or reclaiming your original funds
you don’t need to do anything to claim, it checks in a loop on the background once an hour. mm is supposed to do this automatically, but I’ve never actually seen this work so I’ve reimplemented it in the GUI. (edited)
so obvs due to timing, if the timelock is 2 hours it could be up to ~3 hours before it’s automatically reclaimed because we only check once an hour
but it checks straight away on startup, so if the swap can be resumed as soon as you open the app it will be

**Comment by jdmarlow86** [comment]
Left open for approx 4 hrs yesterday and 6 today. In the Trade history the swap remains in the same state. Screenshot below

![image](https://user-images.githubusercontent.com/22251770/46239159-9b07ef80-c362-11e8-887e-f1a8e59d4470.png)

**Comment by lukechilds** [comment]
@jdmarlow86 did you get this resolved?

**Comment by jorian** [comment]
mm1.0 related
