### ISSUE TITLE
BEER coin disappeared

### ISSUE THREAD

**Issue by osyed** [atomiclabs/hyperdex#574]
**Describe the bug**

I was testing out Hyperdex. I added and removed another coin and it caused Beer coin to disappear from my portfolio.

**To reproduce**

1. Go to Settings tab.
2. Under "Enabled currencies" click on drop down to add a new one.
3. Under "Enabled currencies" click on X to delete the one you just added.
4. Go to Dashboard. Beer used to be listed above Bitcoin and Komodo, but now it is gone. It is not listed under "Enabled currencies" drop down either.

**System info**

- OS & version: Windows 10
- HyperDEX version: 0.2.2

**Additional context**

Even reinstalling Hyperdex and restoring the account does not bring back Beer coin.

**Comment by sindresorhus** [comment]
BEER is only meant for testing, so we've only enabled during development and in nightly releases.

**Comment by osyed** [comment]
Well it was there when I started the HyperDex program. I was able to use the BEER address and receive coins from the faucet. I was also able to create an open order to convert BEER to PIZZA. It just disappeared after I added a new coin and deleted it.

**Comment by sindresorhus** [comment]
We filter the `BEER` currency (based on whether you're running in debug mode or not) when you add/remove a currency. That's why it suddenly disappeared. You probably previously ran a much older HyperDEX version, a nightly build, or HyperDEX in debug-mode, and that's why you had the `BEER` currency enabled. If you really want it back, go to "Help" in the top menu and click "Debug Mode", then you'll be able to enable `BEER` again.

**Comment by osyed** [comment]
Thanks. I was able to enable BEER again. I would say, don't bother trying to filter is based on status of debug mode and checking that when a currency is being added/removed. Just let the user disable it if they want. It will avoid customer service issues.
